### PR TITLE
Adding Dockerfile for container usage

### LINKED ISSUE #23: JoSS Review: Functionality
## Functionality

This is for https://github.com/openjournals/joss-reviews/issues/1637

It's not required, but for the interested user it's sometimes helpful to give them a command to copy paste verbatim to clone the repository. The repository seems big, so a --depth 1 might help:

```bash
$ git clone --depth 1 https://github.com/imr-framework/virtual-scanner
$ cd virtual-scanner
```

There isn't any instruction to install dependencies, although I see the requirements.txt file, and it's immense. It would actually be sort of dangerous to just run this on the host (e.g., pip install -r requirements.txt) so I'd like to suggest that the others provide a Dockerfile that handles this. Anticipating that this is a Flask application, you could provide just a Dockerfile with an entrypoint to handle the database (sqlite?) and web server (if not development) or you could provide a docker-compose. Do any of the authors have experience with containers to support this?

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### Fixes #23 

This pull request will add a basic Dockerfile that the user can build to run the virtual-scanner locally. I haven't tested the full interface yet, but wanted to get to you asap so you can take a look, and possibly check that things are running as they should. I put full instructions in the README for building and then running - let me know if it works for you!

### CODE REVIEW

**Comment by mathieuboudreau** [comment]
Instructions & Dockerfile worked for me 👍

**Comment by vsoch** [comment]
This should be ready to merge - it will make it easier to finish review.

**Comment by tonggehua** [comment]
Instructions & Dockerfile didn't work for me - 
First, when I ran 
```
docker build -t virtualscanner
```
It gave this message:
```
"docker build" requires exactly 1 argument.
```
So I tried
```
docker build virtualscanner
```
During the process,  `requirements.txt`, `setup.py`, and `README.md` couldn't be found and I had to move them into the **virtualscanner** folder inside the main folder. 
Finally, when the process successfully completes and I use
```
docker run -p 5000:5000 virtualscanner
```
This error came up:
```
Unable to find image 'virtualscanner:latest' locally
docker: Error response from daemon: pull access denied for virtualscanner, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
So I used `docker images` to look up the latest image ID and did this instead:
```
docker run -p 5000:5000 c0cfb1cfa339
```
Which produced this:
```
Traceback (most recent call last):
  File "/opt/conda/bin/virtualscanner", line 11, in <module>
    load_entry_point('virtual-scanner==1.0.21', 'console_scripts', 'virtualscanner')()
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'virtualscanner'
```

**Comment by mathieuboudreau** [comment]
Odd, it worked fine for me when I tested it. Which folder were you running your commands from: `virtual-scanner/` or `virtual-scanner/virtualscanner/`?

**Comment by vsoch** [comment]
You are missing a period after the "virtualscanner"

**Comment by vsoch** [comment]
That refers to the context, which is usually the present working directory (indicated by .)

**Comment by vsoch** [comment]
When you then just built with virtual scanner, it used that directory as the context, hence not finding any of the files. So - just add the dot (.) and all will be well! :)

**Comment by vsoch** [comment]
The period is in the dockerfile and instruction, I think you just forgot to copy paste it. 
image

**Comment by tonggehua** [comment]
Thanks! Testing now - it's taking a long time to send build context to Docker daemon

**Comment by vsoch** [comment]
That might mean you have something local that shouldn't be added to the Docker build - any large files, containers, or similar? It shouldn't take super long, so if it is, it's probably something huge that shouldn't be added :P

**Comment by mathieuboudreau** [comment]
I'm a big fan of sharing screen recordings when debugging, so here's the steps I did to run this docker build (& how long it took me).

https://www.youtube.com/watch?v=S-Z8gqpknUg&feature=youtu.be

**Comment by tonggehua** [comment]
It works now, but generates errors on Acquire and Analyze. It seems that things are not being added to the payload, which is how we store inputs from the html. 

Running locally without Docker doesn't generate these errors - we need to investigate a bit and make them work together.

**Comment by vsoch** [comment]
Could you better describe what you mean by “things aren’t added to the payload?”  I didn’t have any issue with running the application itself.

**Comment by tonggehua** [comment]
I can run the application itself on Docker too, but it does generate the error you've mentioned before in #36 (**Run Scan**) and also a similar error in Analyze. Running it with local code doesn't generate these errors.

**Comment by tonggehua** [comment]
I will merge this so it's easier to debug.

**Comment by vsoch** [comment]
okey doke, let me know when you are done and I'll continue review.

**Pull request merged**
